branch-defaults:
  aws-attempts:
    environment: Metanoia
environment-defaults:
  Metanoia:
    branch: null
    repository: null
global:
  application_name: Metanoia
  default_ec2_keyname: metanoia
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
